### ISSUE TITLE
Not able to edit the tags

### ISSUE THREAD

**Issue by manishtiwari25** [linkdotnet/Blog#248] opened 2023-07-19 14:14 UTC
Found a weird issue, instead of coma(,) while adding the tags I mistakenly added a semicolon(;) and saved the post. when I realize my mistake I try to update it, and it is not working. 
could be an issue with EF core, but I am looking into this. 
two things I am looking into
1. the bug
2. adding a helper text on blog post page to let user how to add the tags

**Comment by linkdotnet** [comment] 2023-07-20 05:19
Yes unfortunately. I tracked this bug here: #101 
The problem is that the cached repository retrieves the element when you edit your blog post and therefore child-collections (like Tags) are not retrieved.

SInce EF Core 8 we could migrate the Tags to a inline JSON array. That would solve the issue.
I will close the issue here.

**Closed by linkdotnet** 2023-07-20 05:19 UTC
